# git 올릴때 빼고 올릴것
server:
  port: 8095

navar.api.client-id: Fbdqhslq5uCCrvl6yQKk
navar.api.client-secret: X3343HV9ZA

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: yyy042352@gmail.com
    password: bylpukfcosdgawln
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

  # 여기까지
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://project1.cxg8vdlfu0la.ap-southeast-2.rds.amazonaws.com:3306/dev
#    username: admin
#    password: '00000000'
    url: jdbc:mysql://localhost:3306/project02
    username: root
    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update # DDL?? ??
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  # yaml/yml ?? - Thymeleaf ??
  thymeleaf:
    cache: false
    check-template-location: true
    #    prefix: classpath:/templates/
    #    suffix: .html
    enabled: true


  # application-oauth2.yml 로그인 어스관련
  profiles:
    include: oauth2
  # 여기까지

naver:
  api:
    client-id: Fbdqhslq5uCCrvl6yQKk
    client-secret: X3343HV9ZA

  auth-url: https://auth.worksmobile.com

  org:
    units: /v1.0/orgunits

  auth:
    uri:
      authorize: /oauth2/v2.0/authorize
      token: /oauth2/v2.0/token

  scope: directory,directory.read,orgunit,orgunit.read,user,user.read

  work-url : https://www.worksapis.com

  redirect-url : http://localhost:8095/naver/token
---
spring:
  config:
    activate:
      on-profile: prd

server:
  port: 8095

naver:
  redirect-url: http://13.209.250.6:8095/naver/token

---