spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 819353169413-0t1njq3m97rgtqucvqs6le2ptfm2c09q.apps.googleusercontent.com
            clientSecret: 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
            scope: email, profile


          naver:
            #            client-id: Y9otv3HknXJcGvkvOVfn  예전꺼임
            client-id: Uy8FgIaBU7CLicC1tvxY
            #            client-secret: 4UZgAHM9s8  예전꺼임
            client-secret: i_tuDiPx1C
            redirect-uri: "http://localhost:8095/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope: email, name
            client-name: Naver

          kakao:
            client-id: 943a711bf05346e1b0d9d53f15158cc4
            client-secret: H2uAiJwdmhFZV86PCqKI2qk88eT9VdZ8
            redirect-uri: "http://localhost:8095/login/oauth2/code/kakao"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email #동의 항목
            client-name: Kakao



        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response   # naver가 보내주는 사용자 정보 response ={email, name: }

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

